### ISSUE TITLE
Not reconnecting on JS version

### ISSUE THREAD

**Issue by slpn1** [opentok/opentok-reconnection#18]
I tried to use this in my clients project but more times than not it doesn't reconnect. To see if was just my project I have just tried this demo code with the same issues.

If I kill the internet connection for a second, the status still shows "Connected to session" but the subscriber streams are then frozen and then disappear after 30 seconds or so. Occasionally the subscriber stream starts again, but 75% time it freezes then disappears.

If I wait 5 seconds or so the status changes to 'Disconnected', then 'reconnecting', then 'Reconnected', but i have exactly same problem as above, but this time the publisher steam disappears whilst the subscriber stream stays but frozen.

I haven't modified the code at all. Any ideas?

Thanks,
Simon

**Comment by MichaelJolley** [comment]
Closing as stale. Please open a new issue if needed.
