### ISSUE TITLE
Session Not getting Reconnecting after disconnecting from internet

### ISSUE THREAD

**Issue by Jithesh92** [opentok/opentok-reconnection#21]
Hello,

I have integrated TokBox SDK 2.9.2 in my iOS app.

I am getting error as follows  when the session tries to reconnect to session 

A 1600 error in the subscriber:
subscriber didFailWithError Error Domain=OTSubscriberErrorDomain Code=1600 "Internal error -- WebRTC subscriber error." UserInfo=0x166a8a40 {NSLocalizedDescription=Internal error -- WebRTC subscriber error.}  and it fails to reconnect.

Please look into this and sugguest a resolution for the same as soon as possible.

Regards,
Jithesh

**Comment by Jithesh92** [comment]
Hello,

Please advise on the above mentioned issue as soon as possible so that we need to  implement the same on the live project in ios ..
Waiting for your .

Regards,
Jithesh

**Comment by MichaelJolley** [comment]
Closing as stale. Please open a new issue if needed.
